server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop?serverTimezone=UTC
    username: root
    password: w123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.126.128
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin
dubbo:
  application:
    name: shop_goods_service
  registry:
    address: zookeeper://192.168.126.128:2181
  protocol:
    port: -1
  consumer:
    check: false