spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: 8080
dubbo:
  application:
    name: shop_back1
  registry:
    address: zookeeper://192.168.126.128:2181
fdfs:
  tracker-list: 192.168.126.128:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  serverpath: http://192.168.126.128/